You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 513, in move_wheel_files
    with open_for_csv(record, 'r') as record_in:
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 172, in open_for_csv
    return open(name, mode + bin, **nl)
FileNotFoundError: [Errno 2] No existe el fichero o el directorio: '/home/jlsuarez/.local/lib/python3.6/site-packages/setuptools-39.2.0.dist-info/RECORD'
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "test/test_tfg_dim.py", line 12, in <module>
    from utils import datasets as ds
  File "/home/jlsuarez/pyDML/utils/__init__.py", line 4, in <module>
    from .kfold_tester import kfold_tester_supervised_knn
  File "/home/jlsuarez/pyDML/utils/kfold_tester.py", line 16, in <module>
    from dml import(
  File "/home/jlsuarez/pyDML/dml/__init__.py", line 6, in <module>
    from .pca import PCA
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/usr/local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/usr/local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
/home2/sge/default/spool/node25/job_scripts/247980: línea 24: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247980: línea 25: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247980: línea 26: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247980: línea 27: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247980: línea 28: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247980: línea 29: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247980: línea 30: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247980: línea 32: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247980: línea 33: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247980: línea 35: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 24: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 25: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 26: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 27: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 28: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 29: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 30: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 32: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 33: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247983: línea 35: python3.6: no se encontró la orden
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Necesita ser usuario root para poder ejecutar este comando.
/home2/sge/default/spool/node25/job_scripts/247984: línea 26: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247984: línea 27: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247984: línea 28: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247984: línea 29: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247984: línea 30: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247984: línea 31: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247984: línea 32: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247984: línea 34: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247984: línea 35: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247984: línea 37: python3.6: no se encontró la orden
sudo: sorry, you must have a tty to run sudo
/home2/sge/default/spool/node25/job_scripts/247985: línea 26: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247985: línea 27: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247985: línea 28: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247985: línea 29: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247985: línea 30: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247985: línea 31: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247985: línea 32: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247985: línea 34: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247985: línea 35: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247985: línea 37: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 24: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 25: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 26: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 27: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 28: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 29: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 30: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 32: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 33: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247986: línea 35: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 24: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 25: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 26: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 27: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 28: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 29: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 30: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 32: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 33: python3.6: no se encontró la orden
/home2/sge/default/spool/node25/job_scripts/247987: línea 35: python3.6: no se encontró la orden
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/jlsuarez/pyDML/dml/dml_algorithm.py:58: ComplexWarning: Casting complex values to real discards the imaginary part
  L = metric_to_linear(self.metric())
/home/jlsuarez/.local/lib/python3.6/site-packages/numpy/core/numeric.py:492: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:433: ComplexWarning: Casting complex values to real discards the imaginary part
  array = np.array(array, dtype=dtype, order=order, copy=copy)
/usr/local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
